<BookScreen>:
    BoxLayout:
        MDFillRoundFlatButton:
            style: "tonal"
            theme_width: "Custom"
            height: "56dp"
            size_hint_x: .5

            MDIconButton:
                x: text.x - (self.width + dp(10))
                icon: "plus"

            MDTextButton:
                id: text
                text: "Tonal"
                pos_hint: {"center_x": .5, "center_y": .5}